### PR TITLE
Boresha Afya Fixes: App crashes when a user clicks on a ANC profile's View house location

### LINKED ISSUE #2079: Boresha Afya Fixes: App crashes when a user clicks on a ANC profile's View house location
APK - Kituoni (HF)
Android 7

When one clicks on an ANC Profile to View House Location the App crashes. See the following logs.
```
07-04 16:06:16.147  1259  6724 I ActivityTaskManager: START u0 {cmp=org.smartregister.chw.hf/org.smartregister.chw.core.activity.CoreAncMemberMapActivity (has extras)} from uid 10337
		07-04 16:06:16.148 30551 30551 D AndroidRuntime: Shutting down VM
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: FATAL EXCEPTION: main
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: Process: org.smartregister.chw.hf, PID: 30551
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: android.content.ActivityNotFoundException: Unable to find explicit activity class {org.smartregister.chw.hf/org.smartregister.chw.core.activity.CoreAncMemberMapActivity}; have you declared this activity in your AndroidManifest.xml?
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2078)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5377)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5335)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:5721)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:5674)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at org.smartregister.chw.core.activity.CoreAncMemberProfileActivity.openFamilyLocation(CoreAncMemberProfileActivity.java:276)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at org.smartregister.chw.anc.activity.BaseAncMemberProfileActivity.onClick(BaseAncMemberProfileActivity.java:495)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at org.smartregister.chw.core.activity.CoreAncMemberProfileActivity.onClick(CoreAncMemberProfileActivity.java:160)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.view.View.performClick(View.java:8160)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:8137)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.view.View.access$3700(View.java:888)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:30236)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8653)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
		07-04 16:06:16.156  1259  7733 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
		07-04 16:06:16.156  5257  5330 D NetworkController.SecMobileSignalController(1/1): onSignalStrengthsChanged level=4
		07-04 16:06:16.157  1259  6724 D Debug   : low && ship && 3rd party app crash, so skip dump

```

### PR DESCRIPTION
**Pull request by owais-vd**
close https://github.com/opensrp/opensrp-client-chw/issues/2079

### CODE REVIEW

File: opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/HealthFacilityApplication.java [hunk 1]
```diff
@@ -227,8 +226,6 @@ public void onCreate() {
         }
         // set up processor
         FamilyLibrary.getInstance().setClientProcessorForJava(HfClientProcessor.getInstance(getApplicationContext()));
-
-        Mapbox.getInstance(this, BuildConfig.MAPBOX_SDK_ACCESS_TOKEN);
```
Comment (ekigamba) [inline opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/HealthFacilityApplication.java]: I think we can leave this here

File: opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/activity/FamilyRegisterActivity.java [hunk 2]
```diff
@@ -57,6 +58,7 @@ protected void registerBottomNavigation() {
     @Override
     protected void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
+        Mapbox.getInstance(this, BuildConfig.MAPBOX_SDK_ACCESS_TOKEN);
         NavigationMenu.getInstance(this, null, null);
```
Comment (ekigamba) [inline opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/activity/FamilyRegisterActivity.java]: We should remove the previous one from the `strings.xml` also

**Review by ekigamba — CHANGES_REQUESTED** [review]

File: opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/HealthFacilityApplication.java (hunk 1 above)
Comment (owais-vd) [reply opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/HealthFacilityApplication.java]: I've moved to the App level but PR failed with 
```java
org.smartregister.chw.hf.activity.LoginActivityTest > testUserNameEditTextIsInitialized FAILED
    java.lang.ExceptionInInitializerError at ConnectivityReceiver.java:43
        Caused by: java.lang.NullPointerException at File.java:279
```

moving back to the `FamilyRegisterActivity.java`

File: opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/activity/FamilyRegisterActivity.java (hunk 2 above)
Comment (owais-vd) [reply opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/activity/FamilyRegisterActivity.java]: removed. https://github.com/opensrp/opensrp-client-chw-hf/pull/136/files#diff-3d9187c767fa812c258fb0d6b5ab2ebc68d2dfd35cba2bec205ee6ffdd988a1dL31

Comment (allan-on) [reply opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/activity/FamilyRegisterActivity.java]: Why isn't this initialization done in the Application class?

File: opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/HealthFacilityApplication.java (hunk 1 above)
Comment (ekigamba) [reply opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/HealthFacilityApplication.java]: It's recommended to have it in the Application class instead. I don't think the test failing is a reason to remove it unless the tested functionality on the device is the issue since the tests will still fail. The tests are passing because there is no `FamilyRegisterActivityTest`

Comment (ekigamba) [reply opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/HealthFacilityApplication.java]: I'll still need this in the Application class before approving this PR

Comment (owais-vd) [reply opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/HealthFacilityApplication.java]: done

File: opensrp-chw-hf/build.gradle [hunk 3]
```diff
@@ -178,6 +194,7 @@ dependencies {
     implementation 'com.android.support:multidex:1.0.3'
     //Do not upgrade to 24.jre-1 due to compatibility issues
     implementation 'com.google.guava:guava:20.0'
+    testImplementation project(path: ':opensrp-chw-hf')
```
Comment (ekigamba) [inline opensrp-chw-hf/build.gradle]: Why is this added? It looks like readding the current code module to be accessible in the tests. Isn't this already accessible

**Review by ekigamba — CHANGES_REQUESTED** [review]

File: opensrp-chw-hf/build.gradle (hunk 3 above)
Comment (ekigamba) [reply opensrp-chw-hf/build.gradle]: Else, this PR looks good

Comment (owais-vd) [reply opensrp-chw-hf/build.gradle]: previously it was not accessible, ide suggested to add

Comment (ekigamba) [reply opensrp-chw-hf/build.gradle]: Clean and rebuild your project. I don't see the need to have it here unless the module naming is wrong or the build is corrupted. It was working without this

Comment (owais-vd) [reply opensrp-chw-hf/build.gradle]: done

**Review by ekigamba — APPROVED** [review]
