### PR TITLE
Boresha Afya Fixes: Saving a Family takes more than 5mins

### LINKED ISSUE #2077: Boresha Afya Fixes: Saving a Family takes more than 5mins
APK - Kituoni (Health Facility)
Android version 7

Steps to reproduce:
	a) Click add family
	b) Fill in the fields
	c) Click Submit

See attached video

https://user-images.githubusercontent.com/5908630/176893365-b777aa23-bf32-4836-b0c5-1623c0ed27ed.mp4

.

### PR DESCRIPTION
**Pull request by owais-vd**
close https://github.com/opensrp/opensrp-client-chw/issues/2077, https://github.com/opensrp/opensrp-client-chw/issues/2078

### CODE REVIEW

File: opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/sync/intent/HfSyncTaskIntentService.java [hunk 1]
```diff
@@ -2,17 +2,49 @@
...
+
+import timber.log.Timber;
+
 public class HfSyncTaskIntentService extends SyncTaskIntentService {
     @Override
     protected void onHandleIntent(Intent intent) {
         HfTaskServiceHelper taskServiceHelper = HfTaskServiceHelper.getInstance();
         taskServiceHelper.syncTasks();
-        SyncTaskWithClientEventsServiceJob.scheduleJobImmediately(SyncTaskWithClientEventsServiceJob.TAG);
+        scheduleJob(SyncTaskWithClientEventsServiceJob.TAG, 15L, 5L);
```
Comment (allan-on) [inline opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/sync/intent/HfSyncTaskIntentService.java]: Why not schedule the job periodically like in https://github.com/opensrp/opensrp-client-chw-hf/blob/master/opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/interactor/LoginInteractor.java#L42

Comment (owais-vd) [reply opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/sync/intent/HfSyncTaskIntentService.java]: seems to have a bug in `scheduleJob()` method we are passing the `start` param as a minute and matching the condition with milliseconds. 

https://github.com/opensrp/opensrp-client-core/blob/d24dc795ad2e2583447ef59042c0afb0691ae154/opensrp-core/src/main/java/org/smartregister/job/BaseJob.java#L26
Line no 26 will always return false.

I think we need to convert `start` to `TimeUnit.MINUTES.toMillis(start)` in client-core library.

**Comment by ekigamba** [comment]
@owais-vd Can you provide a description on what the issue was and the fix?

**Comment by owais-vd** [comment]
> @owais-vd Can you provide a description on what the issue was and the fix?

on the application load, `SyncTaskWithClientEventsServiceJob`  job schedule immediately and blocked the `processClient` method. i made the schedule with delay to prevent the `processClient` method from being blocked.

File: opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/sync/intent/HfSyncTaskIntentService.java (hunk 1 above)
Comment (allan-on) [reply opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/sync/intent/HfSyncTaskIntentService.java]: Hi @owais-vd 
Yes, it appears the comparison `boolean toReschedule = start < TimeUnit.MINUTES.toMillis(15);` is evaluated as  `TimeUnit.MINUTES.toMinutes(15) < TimeUnit.MINUTES.toMillis(start)`. 
Won't this always result to  `toReschedule` as **`true`**?

Comment (owais-vd) [reply opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/sync/intent/HfSyncTaskIntentService.java]: `TimeUnit.MINUTES.toMinutes(15)` always return minutes no conversion would be done because we are converting minutes to minutes.

For example: 
`TimeUnit.MINUTES.toMinutes(15)` return `15` and `TimeUnit.MINUTES.toMillis(15)` return `900000`. Therefore, `toReschedule` will always `true`.

Line no 26 should be changed to `boolean toReschedule = TimeUnit.MINUTES.toMillis(start) < TimeUnit.MINUTES.toMillis(15);`

Comment (allan-on) [reply opensrp-chw-hf/src/main/java/org/smartregister/chw/hf/sync/intent/HfSyncTaskIntentService.java]: Yeah. The change makes sense

**Comment by allan-on** [comment]
Hi @owais-vd 
The `boolean toReschedule = TimeUnit.MINUTES.toMillis(start) < TimeUnit.MINUTES.toMillis(15);` change makes sense.
Did you try testing a fix with scheduling periodically instead prior to writing the custom implementation?

**Comment by owais-vd** [comment]
> Hi @owais-vd The `boolean toReschedule = TimeUnit.MINUTES.toMillis(start) < TimeUnit.MINUTES.toMillis(15);` change makes sense. Did you try testing a fix with scheduling periodically instead prior to writing the custom implementation?

Hi, i didn't check with default scheduling periodically method. I'll check and confirm

**Review by allan-on — DISMISSED** [review]

**Comment by ekigamba** [comment]
The branch cannot currently be merged with unverified commits in it's history and will require a re-write or force-merge

**Comment by ekigamba** [comment]
@allan-on Kindly approve again. The difference is that I removed 2 unsigned commits by Owais. The following are the commits

```
commit 30a9915b1b5eec583012d4d17e25236ca55c2e36
Author: owais <syedowaisali@users.noreply.github.com>
Date:   Fri Jul 29 11:47:15 2022 +0500

    Revert "Merge branch 'master' into issue-2077"
    
    This reverts commit 7a9a6556d2432452d5ab7f1314be566994966774.

commit eaa979ed0185785818f5fc4e7e6c513f996ce26c
Author: owais <syedowaisali@users.noreply.github.com>
Date:   Fri Jul 29 15:24:49 2022 +0500

    trigger build
```

**Review by allan-on — APPROVED** [review]
